{
 "title": "Car Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "car_speed", "legendFormat": "{{driver}}" }
   ]
  },
  {
   "title": "Number of Drives Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "car_driveTime_seconds_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Car Lock",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "targets": [
    { "expr": "car_locked", "legendFormat": "lock state" }
   ]
  },
  {
   "title": "Speed Summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 6 },
   "targets": [
    { "expr": "car_speedSummary_kph", "legendFormat": "Percentile {{quantile}}" }
   ]
  }
 ]
}